import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import "bootstrap/dist/css/bootstrap.css";
import "rodal/lib/rodal.css";

export const metadata: Metadata = {
  title: "QuickFix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
